---
title: "Scrape"
author: "Barry Bullas"
date: "27/08/2019"
output: html_document
---

# Project Aim
The aim of this project is to be able to scrape the player statistics from the [Premier League Website](https://fantasy.premierleague.com/statistics).

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

list_of_packages <- c("rvest", "dplyr")
new_packages <- list_of_packages[!(list_of_packages %in% installed.packages()[,"Package"])]
if(length(new_packages)) install.packages(new_packages)

#Load required packages
lapply(list_of_packages, library, character.only = TRUE)
```

## Basket Ball example
This examples gathers the data for the NBA in 2018.

```{r}
#https://m-clark.github.io/webR/web_scraping.html
nba_url = "http://www.basketball-reference.com/leagues/NBA_2018_totals.html"

bball = read_html(nba_url) %>% 
  html_node("#totals_stats") %>%                       # grab element with id 'total_stats'
  html_table() %>%                                     # the data
  filter(Rk != "Rk") %>%                               # remove header rows
  mutate_at(vars(-Player, -Pos, -Tm), as.numeric)      # convert to numeric

str(bball)

```

## Rangers
This code attempts to get the table of Directors of Glasgow Rangers FC from the [Rangers wikipdeia page](https://en.wikipedia.org/wiki/Rangers_F.C.).

```{r}
rfc_url <- 'https://en.wikipedia.org/wiki/Rangers_F.C.'

rfc = read_html(rfc_url) %>% 
  html_table(fill=TRUE) 

rfc <- rfc[[19]]
rfc

```


## Premier League

```{r}
pl_url <- "https://fantasy.premierleague.com/statistics"

pl = read_html(pl_url) %>% 
  html_table(fill=TRUE)

str(pl)
```

